#!/bin/bash
#
# mci-background-jobs        start/stop/status script
#
# chkconfig: - 64 36
# description: The mci-background-jobs shared health record system
# processname: mci-background-jobs
# config: /etc/default/mci-background-jobs
# pidfile: /var/run/mci-background-jobs/mci-background-jobs.pid
### BEGIN INIT INFO
# Provides: mci-background-jobs
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop mci-background-jobs system,
# Description: BDSHR system
### END INIT INFO

export MCI_BACKGROUND_JOBS_USER=sharedhealth
export MCI_BACKGROUND_JOBS_RUN=/opt/mci-background-jobs/bin/start.sh
export CUR_USER=`/usr/bin/whoami`

# load configuration
. /etc/default/mci-background-jobs

create_dirs() {
    if [[ ! -e /var/run/mci-background-jobs ]]; then
        ln -s /opt/mci-background-jobs/var /var/run/mci-background-jobs
    fi

    if [[ ! -e /var/log/mci-background-jobs ]]; then
        mkdir /var/log/mci-background-jobs
    fi
}
mci_background_jobs_pid() {
        echo `ps -fe | grep "mci-background-jobs.jar" | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(mci_background_jobs_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService mci-background-jobs is already running (pid: $pid)\e[00m"
    else
        # Start mci-background-jobs
        create_dirs
        echo -e "\e[00;32mStarting mci-background-jobs\e[00m"
        if [ `user_exists $MCI_BACKGROUND_JOBS_USER` = "1" ]  && [ "$CUR_USER" != "$MCI_BACKGROUND_JOBS_USER" ] ;
        then
                /bin/su $MCI_BACKGROUND_JOBS_USER -c $MCI_BACKGROUND_JOBS_RUN
        else
                sh $MCI_BACKGROUND_JOBS_RUN
        fi
  fi
  return 0
}
status(){
          pid=$(mci_background_jobs_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService mci-background-jobs is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService mci-background-jobs is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating mci-background-jobs\e[00m"
	kill -9 $(mci_background_jobs_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0